
import { DiagnosisData, FormulatedChallenge, FunnelStage, InvolvementLevel, Language, UIStringKeys, HelpTopic } from './types';

// FIX: Updated to 'gemini-3-pro-preview' for Complex Text Tasks (Strategy & Reasoning)
export const GEMINI_MODEL_TEXT = 'gemini-3-pro-preview';

export const initialDiagnosisData: DiagnosisData = {
  clientName: '',
  projectBudget: '', 
  briefingFileName: null,
  briefingFileContent: null,
  manualBriefingText: '',
  screenshots: [],
  customerType: '',
  market: '',
  sector: '',
  productOrService: '',
  businessChallenge: '',
  customerChallenge: '',
  consumerContext: {
    involvement: '',
    funnelStage: '',
    barriers: '',
  },
  currentStrategyAttempt: '',
};

export const initialFormulatedChallenge: FormulatedChallenge = {
  culturalTension: '',
  marketOpportunity: '',
  consumerInsight: '',
  rumeltDiagnosis: '', // Changed from decisionTension
  rumeltGuidingPolicy: '', // New field
  behavioralJustification: '',
  keyAssumptions: '',
  relevantMentalModels: '',
};

export const defaultFunnelStages: FunnelStage[] = [
  FunnelStage.AWARENESS,
  FunnelStage.CONSIDERATION,
  FunnelStage.DECISION,
  FunnelStage.LOYALTY,
  FunnelStage.RETENTION,
  FunnelStage.ADVOCACY,
];

export const defaultInvolvementLevels: InvolvementLevel[] = [
  InvolvementLevel.LOW,
  InvolvementLevel.MEDIUM,
  InvolvementLevel.HIGH,
];

export const translations: Record<Language, Record<UIStringKeys, string>> = {
  [Language.EN]: {
    [UIStringKeys.AppName]: "Challenge Definition",
    [UIStringKeys.AppSubtitle]: "Crafting Strategic Clarity, Together.",
    [UIStringKeys.FooterStep]: "Step {current} of {total}",
    
    // History
    [UIStringKeys.ButtonHistory]: "History",
    [UIStringKeys.ButtonNewSession]: "New Session",
    [UIStringKeys.HistoryModalTitle]: "Saved Strategy Sessions",
    [UIStringKeys.HistoryEmpty]: "No saved sessions found.",
    [UIStringKeys.LabelLastModified]: "Last Modified",
    [UIStringKeys.ButtonLoad]: "Load",
    [UIStringKeys.ButtonDelete]: "Delete",
    [UIStringKeys.ConfirmDelete]: "Are you sure you want to delete this session?",
    [UIStringKeys.NewSessionConfirm]: "Start a new session? Unsaved progress will be lost.",

    [UIStringKeys.HelpButtonTooltip]: "Help & User Guide",
    [UIStringKeys.HelpModalTitle]: "DM 2. Challenge Definition Helper",
    [UIStringKeys.HelpModalIntro]: "Hello! I'm your assistant for DM 2. Challenge Definition. Select a topic below for guidance.",
    [UIStringKeys.HelpModalDefaultContent]: "Please select a topic from the menu to see help information.",
    [UIStringKeys.HelpModalCloseButtonSR]: "Close help modal",
    [UIStringKeys.HelpModalTopicsHeader]: "Help Topics",

    [UIStringKeys.HelpTopic_Overview_Q]: "What is DM 2. Challenge Definition?",
    [UIStringKeys.HelpTopic_Overview_A]: "DM 2. Challenge Definition is an intelligent tool designed to help you formulate strategic marketing or business challenges. It guides you through diagnosis, AI-powered challenge formulation based on Richard Rumelt's 'Good Strategy, Bad Strategy' principles (Diagnosis and Guiding Policy), and smart prompt generation for ideation, culminating in a shareable summary.",
    [UIStringKeys.HelpTopic_Diagnosis_Q]: "How do I complete the Diagnosis step?",
    [UIStringKeys.HelpTopic_Diagnosis_A]: "In the Diagnosis step, provide detailed information about your:\n- Client Name & Project Briefing (PDF)\n- Project Budget\n- Target Customer Type/Persona\n- Market/Category\n- Sector/Industry\n- Product or Service\n- The Business Challenge (company's problem) & The Customer Challenge (end-user's problem)\n- Consumer Context (Involvement, Funnel Stage, Barriers)\n- Current Strategy Attempts (optional).\nThe more detailed your input, the better the AI-generated insights for Rumelt's Diagnosis and Guiding Policy will be.",
    [UIStringKeys.HelpTopic_ChallengeFormulation_Q]: "Understanding Challenge Formulation (Rumelt's Diagnosis, Guiding Policy, etc.)",
    [UIStringKeys.HelpTopic_ChallengeFormulation_A]: "Based on your Diagnosis input, the AI generates a Strategic Challenge Kernel according to Richard Rumelt:\n- **Rumelt's Diagnosis:** A clear identification of the critical challenge the business faces.\n- **Rumelt's Guiding Policy:** The overall approach to overcome the diagnosed challenge.\n- **Behavioral Justification:** A principle from psychology or behavioral economics (e.g., Mere-Exposure Effect, Social Proof) that explains *why* the Guiding Policy is likely to succeed with human beings.\n- **Cultural Tension:** A significant cultural shift creating unmet needs, providing context.\n- **Market Opportunity:** An actionable opportunity within the market, relevant to the diagnosis.\n- **Consumer Insight:** A deep understanding of your target consumer, informing the diagnosis.\n- **Key Assumptions:** Critical assumptions underpinning the challenge.\n- **Relevant Mental Models:** Strategic frameworks, possibly Rumelt's Sources of Power.\nYou can review and refine these components.",
    [UIStringKeys.HelpTopic_SmartPrompts_Q]: "How can I use the Smart Prompts?",
    [UIStringKeys.HelpTopic_SmartPrompts_A]: "The Smart Prompts are AI-generated based on your formulated Rumelt's Diagnosis and Guiding Policy. They are designed to be open-ended, action-oriented, and thought-provoking to fuel ideation sessions for 'Coherent Actions' (campaigns, products, services, messaging) that effectively implement the Guiding Policy.",
    [UIStringKeys.HelpTopic_Export_Q]: "How can I save or share my work?",
    [UIStringKeys.HelpTopic_Export_A]: "In the final \"Summary & Export\" step, you can review all the information from your session.\nUse the \"Copy to Clipboard\" button to copy the entire summary in Markdown format.\nUse the \"Download as .md File\" button to save the summary as a Markdown file for easy sharing and future reference.",
    [UIStringKeys.HelpTopic_AIGeneration_Q]: "How does AI generation work? What if I see errors?",
    [UIStringKeys.HelpTopic_AIGeneration_A]: "DM 2. Challenge Definition uses Google's Gemini AI to analyze your inputs and generate strategic insights and prompts based on Rumelt's framework.\nIf you encounter errors:\n- Ensure all required fields in the Diagnosis step are filled comprehensively.\n- Check your internet connection.\n- Try regenerating the content. If the issue persists, the AI service might be temporarily unavailable.",
    [UIStringKeys.HelpTopic_Navigation_Q]: "How do I move between steps?",
    [UIStringKeys.HelpTopic_Navigation_A]: "Use the \"Next\" and \"Back\" buttons at the bottom of the page to navigate sequentially through the steps.\nYou can also click on the step names in the progress stepper at the top to jump to a previously completed step or the current step.",

    [UIStringKeys.FeedbackButtonTooltip]: "Send Feedback",
    [UIStringKeys.FeedbackEmailSubject]: "Feedback about DM 2. Challenge Definition",
    [UIStringKeys.FeedbackEmailBody]: "Hello LLYC Team,\n\nI'd like to provide the following feedback regarding the DM 2. Challenge Definition application:\n\n[Please describe your feedback here, including any suggestions or issues encountered.]\n\nThank you.",
    
    [UIStringKeys.ButtonBack]: "Back",
    [UIStringKeys.ButtonNext]: "Next",
    [UIStringKeys.ButtonGenerateStrategicChallenge]: "Generate Strategic Challenge Kernel",
    [UIStringKeys.ButtonRegenerateChallenge]: "Regenerate Challenge Kernel",
    [UIStringKeys.ButtonGenerateSmartPrompts]: "Generate Smart Prompts for Coherent Actions",
    [UIStringKeys.ButtonRegeneratePrompts]: "Regenerate Prompts",
    [UIStringKeys.CopyToClipboard]: "Copy to Clipboard",
    [UIStringKeys.DownloadAsMD]: "Download as .md File",
    [UIStringKeys.ResultsCopied]: "Results copied to clipboard!",
    [UIStringKeys.FailedToCopyResults]: "Failed to copy results: ",
    [UIStringKeys.ButtonChooseFile]: "Choose File",
    [UIStringKeys.ButtonRemoveFile]: "Remove File",
    [UIStringKeys.ButtonUploadImages]: "Choose Images",

    [UIStringKeys.HeaderDiagnosis]: "Initial Diagnosis (Input for AI)",
    [UIStringKeys.HeaderChallengeFormulation]: "Strategic Challenge Kernel (Rumelt)",
    [UIStringKeys.HeaderSmartPrompts]: "Smart Prompt Generation (for Coherent Actions)",
    [UIStringKeys.HeaderResults]: "Strategy Summary & Export",
    [UIStringKeys.HeaderProjectSetup]: "Project Setup",
    [UIStringKeys.HeaderBusinessMarketContext]: "Business & Market Context",
    [UIStringKeys.HeaderProblemConsumerContext]: "Problem & Consumer Context",
    [UIStringKeys.HeaderCurrentEffortsOptional]: "Current Efforts (Optional)",
    [UIStringKeys.HeaderCulturalTension]: "Cultural Tension (Context)",
    [UIStringKeys.HeaderMarketOpportunity]: "Market Opportunity (Context)",
    [UIStringKeys.HeaderConsumerInsight]: "Consumer Insight (Context)",
    [UIStringKeys.HeaderRumeltDiagnosis]: "Rumelt's Diagnosis (The Core Challenge)", 
    [UIStringKeys.HeaderRumeltGuidingPolicy]: "Rumelt's Guiding Policy (The Approach)", 
    [UIStringKeys.HeaderBehavioralJustification]: "Behavioral Justification (Why it works)",
    [UIStringKeys.HeaderKeyAssumptions]: "Key Assumptions",
    [UIStringKeys.HeaderRelevantMentalModels]: "Relevant Mental Models / Rumelt's Sources of Power",
    [UIStringKeys.HeaderGeneratedIdeationPrompts]: "Generated Ideation Prompts (for Coherent Actions)",
    [UIStringKeys.HeaderInformationSources]: "Information Sources",
    [UIStringKeys.HeaderDiagnosisSnapshot]: "Diagnosis Input Snapshot",
    [UIStringKeys.HeaderStrategicChallengeCore]: "Strategic Challenge Kernel (Rumelt)",
        
    [UIStringKeys.DescriptionDiagnosis]: "Let's lay the groundwork. Provide as much detail as possible for a robust strategic analysis by the AI, following Rumelt's principles.",
    [UIStringKeys.DescriptionChallengeFormulation]: "Based on your diagnosis input, the AI will articulate the core Strategic Challenge Kernel: Rumelt's Diagnosis and Guiding Policy. You can then refine it.",
    [UIStringKeys.DescriptionSmartPrompts]: "Leverage the formulated Challenge Kernel to generate tailored prompts for ideation sessions on Coherent Actions (campaigns, products, messages).",
    [UIStringKeys.DescriptionResults]: "Review your complete strategic formulation. You can copy it or download it as a text file.",

    [UIStringKeys.PlaceholderLoading]: "Loading...",
    [UIStringKeys.LabelClientName]: "Client Name",
    [UIStringKeys.PlaceholderNoFileSelected]: "No file selected",
    [UIStringKeys.FileSelected]: "Selected: {fileName}",
    [UIStringKeys.FileParsing]: "Parsing: {fileName}",
    [UIStringKeys.LabelProjectBudget]: "Project Budget (Optional)",
    [UIStringKeys.LabelUploadBriefing]: "Briefing / Inputs",
    [UIStringKeys.LabelBriefingSource]: "Briefing Source",
    [UIStringKeys.TabPDF]: "PDF File",
    [UIStringKeys.TabImages]: "Screenshots",
    [UIStringKeys.TabManualText]: "Manual Input",
    [UIStringKeys.LabelManualBriefing]: "Manual Briefing / Notes",
    [UIStringKeys.PlaceholderManualBriefing]: "Paste text from documents, emails, or describe the situation here...",
    [UIStringKeys.LabelUploadImages]: "Upload Screenshots (Max 5)",
    [UIStringKeys.LabelCustomerType]: "Target Customer Type / Persona",
    [UIStringKeys.PlaceholderCustomerType]: "e.g., SME Founders, Gen Z Gamers",
    [UIStringKeys.LabelMarketCategory]: "Market / Category",
    [UIStringKeys.PlaceholderMarketCategory]: "e.g., B2B SaaS, Sustainable Fashion",
    [UIStringKeys.LabelSectorIndustry]: "Sector / Industry",
    [UIStringKeys.PlaceholderSectorIndustry]: "e.g., Fintech, Healthcare Tech",
    [UIStringKeys.LabelProductService]: "Product or Service Name/Type",
    [UIStringKeys.PlaceholderProductService]: "e.g., AI-powered CRM, Organic Skincare Line",
    [UIStringKeys.LabelBusinessChallenge]: "The Business Challenge (What problem does the *company* face?)",
    [UIStringKeys.PlaceholderBusinessChallenge]: "e.g., Stagnant market share, low brand differentiation, inefficient customer acquisition.",
    [UIStringKeys.LabelCustomerChallenge]: "The Customer Challenge (What problem does the *end-user* face?)",
    [UIStringKeys.PlaceholderCustomerChallenge]: "e.g., Overwhelmed by complex software, unable to find sustainable products, feels disconnected from brands.",
    [UIStringKeys.LabelConsumerInvolvement]: "Consumer Involvement Level",
    [UIStringKeys.LabelFunnelStage]: "Typical Funnel Stage for Target Interaction",
    [UIStringKeys.LabelConsumerBarriers]: "Key Consumer Barriers/Frictions",
    [UIStringKeys.PlaceholderConsumerBarriers]: "e.g., High price perception, complex onboarding, lack of trust",
    [UIStringKeys.LabelCurrentStrategy]: "What has been tried so far? (Briefly)",
    [UIStringKeys.PlaceholderCurrentStrategy]: "e.g., Ran social media ads, offered discounts, focused on SEO content",
    [UIStringKeys.AlertNonPDF]: "Please upload a PDF file.",
    [UIStringKeys.PlaceholderAIWillGenerate]: "AI will generate this based on your input, following Rumelt's principles...",
    [UIStringKeys.MessageFormulatingChallenge]: "Formulating Rumelt's Strategic Challenge Kernel... this may take a moment.",
    [UIStringKeys.MessageGeneratingPrompts]: "Generating smart prompts for Coherent Actions... please wait.",
    [UIStringKeys.ErrorGeneric]: "An unknown error occurred.",
    [UIStringKeys.ErrorChallengeNotFormulated]: "Please ensure Rumelt's Diagnosis and Guiding Policy are formulated before generating prompts.",
    [UIStringKeys.ErrorDiagnosisNotComplete]: "Please complete all core fields in the Diagnosis step before generating the challenge kernel.",
    [UIStringKeys.TextNotSet]: "Not set",
    [UIStringKeys.TextNotGenerated]: "Not generated",
    [UIStringKeys.TextNoPromptsGenerated]: "No prompts generated yet.",
    [UIStringKeys.SelectDefaultOption]: "Select an option...",

    [UIStringKeys.LanguageToggleEN]: "EN",
    [UIStringKeys.LanguageToggleES]: "ES",

    [UIStringKeys.StepperAriaLabel]: "Progress",
    [UIStringKeys.LoadingSpinnerSR]: "Loading...",
  },
  [Language.ES]: {
    [UIStringKeys.AppName]: "Definición del Reto", 
    [UIStringKeys.AppSubtitle]: "Creando claridad estratégica, juntos.",
    [UIStringKeys.FooterStep]: "Paso {current} de {total}",

    // History
    [UIStringKeys.ButtonHistory]: "Historial",
    [UIStringKeys.ButtonNewSession]: "Nueva Sesión",
    [UIStringKeys.HistoryModalTitle]: "Sesiones Guardadas",
    [UIStringKeys.HistoryEmpty]: "No se encontraron sesiones guardadas.",
    [UIStringKeys.LabelLastModified]: "Última Modificación",
    [UIStringKeys.ButtonLoad]: "Cargar",
    [UIStringKeys.ButtonDelete]: "Borrar",
    [UIStringKeys.ConfirmDelete]: "¿Seguro que quieres borrar esta sesión?",
    [UIStringKeys.NewSessionConfirm]: "¿Iniciar nueva sesión? Se perderá el progreso no guardado.",

    [UIStringKeys.HelpButtonTooltip]: "Ayuda y Guía de Usuario",
    [UIStringKeys.HelpModalTitle]: "Ayudante de DM 2. Definición del Reto",
    [UIStringKeys.HelpModalIntro]: "¡Hola! Soy tu asistente para DM 2. Definición del Reto. Selecciona un tema de la lista para obtener ayuda.",
    [UIStringKeys.HelpModalDefaultContent]: "Por favor, selecciona un tema del menú para ver la información de ayuda.",
    [UIStringKeys.HelpModalCloseButtonSR]: "Cerrar modal de ayuda",
    [UIStringKeys.HelpModalTopicsHeader]: "Temas de Ayuda",

    [UIStringKeys.HelpTopic_Overview_Q]: "¿Qué es DM 2. Definición del Reto?",
    [UIStringKeys.HelpTopic_Overview_A]: "DM 2. Definición del Reto es una herramienta inteligente diseñada para ayudarte a formular retos estratégicos de marketing o negocio. Te guía a través del diagnóstico, la formulación de retos asistida por IA basada en los principios de 'Buena Estrategia, Mala Estrategia' de Richard Rumelt (Diagnóstico y Política Guía), y la generación de prompts inteligentes para la ideación, culminando en un resumen compartible.",
    [UIStringKeys.HelpTopic_Diagnosis_Q]: "¿Cómo completo el paso de Diagnóstico?",
    [UIStringKeys.HelpTopic_Diagnosis_A]: "En el paso de Diagnóstico, proporciona información detallada sobre tu:\n- Nombre del Cliente y Resumen del Proyecto (PDF)\n- Presupuesto del Proyecto\n- Tipo de Cliente Objetivo/Persona\n- Mercado/Categoría\n- Sector/Industria\n- Producto o Servicio\n- El Reto de Negocio (problema de la empresa) y El Reto del Cliente (problema del usuario final)\n- Contexto del Consumidor (Implicación, Etapa del Embudo, Barreras)\n- Intentos de Estrategia Actuales (opcional).\nCuanto más detallada sea tu entrada, mejores serán los insights generados por la IA para el Diagnóstico y la Política Guía de Rumelt.",
    [UIStringKeys.HelpTopic_ChallengeFormulation_Q]: "Entendiendo la Formulación del Reto (Diagnóstico de Rumelt, Política Guía, etc.)",
    [UIStringKeys.HelpTopic_ChallengeFormulation_A]: "Basado en tu Diagnóstico, la IA genera un Núcleo de Reto Estratégico según Richard Rumelt:\n- **Diagnóstico de Rumelt:** Una identificación clara del reto crítico que enfrenta el negocio.\n- **Política Guía de Rumelt:** El enfoque general para superar el reto diagnosticado.\n- **Justificación Conductual:** Un principio de la psicología o economía conductual (ej. Efecto de Mera Exposición, Prueba Social) que explica *por qué* la Política Guía es propensa a funcionar con seres humanos.\n- **Tensión Cultural:** Un cambio cultural significativo que crea necesidades no satisfechas, proporcionando contexto.\n- **Oportunidad de Mercado:** Una oportunidad accionable dentro del mercado, relevante para el diagnóstico.\n- **Insight del Consumidor:** Un entendimiento profundo de tu consumidor objetivo, informando el diagnóstico.\n- **Suposiciones Clave:** Suposiciones críticas que sustentan el reto.\n- **Modelos Mentales Relevantes:** Marcos estratégicos, posiblemente las Fuentes de Poder de Rumelt.\nPuedes revisar y refinar estos componentes generados por IA.",
    [UIStringKeys.HelpTopic_SmartPrompts_Q]: "¿Cómo puedo usar los Prompts Inteligentes?",
    [UIStringKeys.HelpTopic_SmartPrompts_A]: "Los Prompts Inteligentes son generados por IA basados en tu Diagnóstico y Política Guía de Rumelt formulados. Están diseñados para ser abiertos, orientados a la acción y estimulantes para impulsar sesiones de ideación para 'Acciones Coherentes' (campañas, productos, servicios, mensajes) que implementen eficazmente la Política Guía.",
    [UIStringKeys.HelpTopic_Export_Q]: "¿Cómo puedo guardar o compartir mi trabajo?",
    [UIStringKeys.HelpTopic_Export_A]: "En el paso final \"Resumen y Exportación\", puedes revisar toda la información de tu sesión.\nUsa el botón \"Copiar al Portapapeles\" para copiar el resumen completo en formato Markdown.\nUsa el botón \"Descargar como Archivo .md\" para guardar el resumen como un archivo Markdown para compartir fácilmente y referencia futura.",
    [UIStringKeys.HelpTopic_AIGeneration_Q]: "¿Cómo funciona la generación por IA? ¿Qué pasa si veo errores?",
    [UIStringKeys.HelpTopic_AIGeneration_A]: "DM 2. Definición del Reto utiliza la IA Gemini de Google para analizar tus entradas y generar insights estratégicos y prompts basados en el marco de Rumelt.\nSi encuentras errores:\n- Asegúrate de que todos los campos requeridos en el paso de Diagnóstico estén completos.\n- Verifica tu conexión a internet.\n- Intenta regenerar el contenido. Si el problema persiste, el servicio de IA podría estar temporalmente no disponible.",
    [UIStringKeys.HelpTopic_Navigation_Q]: "¿Cómo me muevo entre los pasos?",
    [UIStringKeys.HelpTopic_Navigation_A]: "Usa los botones \"Siguiente\" y \"Anterior\" en la parte inferior de la página para navegar secuencialmente a través de los pasos.\nTambién puedes hacer clic en los nombres de los pasos en el indicador de progreso en la parte superior para saltar a un paso previamente completado o al paso actual.",

    [UIStringKeys.FeedbackButtonTooltip]: "Enviar Feedback",
    [UIStringKeys.FeedbackEmailSubject]: "Feedback sobre DM 2. Definición del Reto",
    [UIStringKeys.FeedbackEmailBody]: "Hola Equipo LLYC,\n\nMe gustaría proporcionar el siguiente feedback sobre la aplicación DM 2. Definición del Reto:\n\n[Por favor, describe tu feedback aquí, incluyendo sugerencias o problemas encontrados.]\n\nGracias.",

    [UIStringKeys.ButtonBack]: "Anterior",
    [UIStringKeys.ButtonNext]: "Siguiente",
    [UIStringKeys.ButtonGenerateStrategicChallenge]: "Generar Núcleo del Reto Estratégico",
    [UIStringKeys.ButtonRegenerateChallenge]: "Regenerar Núcleo del Reto",
    [UIStringKeys.ButtonGenerateSmartPrompts]: "Generar Prompts Inteligentes para Acciones Coherentes",
    [UIStringKeys.ButtonRegeneratePrompts]: "Regenerar Prompts",
    [UIStringKeys.CopyToClipboard]: "Copiar al Portapapeles",
    [UIStringKeys.DownloadAsMD]: "Descargar como .md",
    [UIStringKeys.ResultsCopied]: "¡Resultados copiados al portapapeles!",
    [UIStringKeys.FailedToCopyResults]: "Error al copiar resultados: ",
    [UIStringKeys.ButtonChooseFile]: "Elegir Archivo",
    [UIStringKeys.ButtonRemoveFile]: "Eliminar Archivo",
    [UIStringKeys.ButtonUploadImages]: "Elegir Imágenes",
    
    [UIStringKeys.HeaderDiagnosis]: "Diagnóstico Inicial (Entrada para IA)",
    [UIStringKeys.HeaderChallengeFormulation]: "Núcleo del Reto Estratégico (Rumelt)",
    [UIStringKeys.HeaderSmartPrompts]: "Generación de Prompts Inteligentes (para Acciones Coherentes)",
    [UIStringKeys.HeaderResults]: "Resumen y Exportación de Estrategia",
    [UIStringKeys.HeaderProjectSetup]: "Configuración del Proyecto",
    [UIStringKeys.HeaderBusinessMarketContext]: "Contexto de Negocio y Mercado",
    [UIStringKeys.HeaderProblemConsumerContext]: "Problema y Contexto del Consumidor",
    [UIStringKeys.HeaderCurrentEffortsOptional]: "Esfuerzos Actuales (Opcional)",
    [UIStringKeys.HeaderCulturalTension]: "Tensión Cultural (Contexto)",
    [UIStringKeys.HeaderMarketOpportunity]: "Oportunidad de Mercado (Contexto)",
    [UIStringKeys.HeaderConsumerInsight]: "Insight del Consumidor (Contexto)",
    [UIStringKeys.HeaderRumeltDiagnosis]: "Diagnóstico de Rumelt (El Reto Central)", 
    [UIStringKeys.HeaderRumeltGuidingPolicy]: "Política Guía de Rumelt (El Enfoque)", 
    [UIStringKeys.HeaderBehavioralJustification]: "Justificación Conductual (Por qué funciona)",
    [UIStringKeys.HeaderKeyAssumptions]: "Suposiciones Clave",
    [UIStringKeys.HeaderRelevantMentalModels]: "Modelos Mentales Relevantes / Fuentes de Poder de Rumelt",
    [UIStringKeys.HeaderGeneratedIdeationPrompts]: "Prompts de Ideación Generados (para Acciones Coherentes)",
    [UIStringKeys.HeaderInformationSources]: "Fuentes de Información",
    [UIStringKeys.HeaderDiagnosisSnapshot]: "Resumen del Diagnóstico (Entrada)",
    [UIStringKeys.HeaderStrategicChallengeCore]: "Núcleo del Reto Estratégico (Rumelt)",

    [UIStringKeys.DescriptionDiagnosis]: "Sentemos las bases. Proporciona tantos detalles como sea posible para un análisis estratégico robusto por la IA, siguiendo los principios de Rumelt.",
    [UIStringKeys.DescriptionChallengeFormulation]: "Basándose en tu diagnóstico, la IA articulará el Núcleo del Reto Estratégico: el Diagnóstico y la Política Guía de Rumelt. Luego podrás refinarlo.",
    [UIStringKeys.DescriptionSmartPrompts]: "Aprovecha el Núcleo del Reto formulado para generar prompts personalizados para sesiones de ideación sobre Acciones Coherentes (campañas, productos, mensajes).",
    [UIStringKeys.DescriptionResults]: "Revisa tu formulación estratégica completa. Puedes copiarla o descargarla como un archivo de texto.",

    [UIStringKeys.PlaceholderLoading]: "Cargando...",
    [UIStringKeys.LabelClientName]: "Nombre del Cliente",
    [UIStringKeys.PlaceholderNoFileSelected]: "Ningún archivo seleccionado",
    [UIStringKeys.FileSelected]: "Seleccionado: {fileName}",
    [UIStringKeys.FileParsing]: "Analizando: {fileName}",
    [UIStringKeys.LabelProjectBudget]: "Presupuesto del Proyecto (Opcional)",
    [UIStringKeys.LabelUploadBriefing]: "Briefing / Entradas",
    [UIStringKeys.LabelBriefingSource]: "Fuente del Briefing",
    [UIStringKeys.TabPDF]: "Archivo PDF",
    [UIStringKeys.TabImages]: "Pantallazos",
    [UIStringKeys.TabManualText]: "Entrada Manual",
    [UIStringKeys.LabelManualBriefing]: "Briefing Manual / Notas",
    [UIStringKeys.PlaceholderManualBriefing]: "Pega texto de documentos, correos, o describe la situación aquí...",
    [UIStringKeys.LabelUploadImages]: "Subir Pantallazos (Máx 5)",
    [UIStringKeys.LabelCustomerType]: "Tipo de Cliente / Persona Objetivo",
    [UIStringKeys.PlaceholderCustomerType]: "Ej: Fundadores de PYMEs, Gamers Gen Z",
    [UIStringKeys.LabelMarketCategory]: "Mercado / Categoría",
    [UIStringKeys.PlaceholderMarketCategory]: "Ej: SaaS B2B, Moda Sostenible",
    [UIStringKeys.LabelSectorIndustry]: "Sector / Industria",
    [UIStringKeys.PlaceholderSectorIndustry]: "Ej: Fintech, Tecnología Sanitaria",
    [UIStringKeys.LabelProductService]: "Nombre/Tipo de Producto o Servicio",
    [UIStringKeys.PlaceholderProductService]: "Ej: CRM con IA, Línea de Cosmética Orgánica",
    [UIStringKeys.LabelBusinessChallenge]: "El Reto de Negocio (¿Qué problema enfrenta la *empresa*?)",
    [UIStringKeys.PlaceholderBusinessChallenge]: "Ej: Cuota de mercado estancada, baja diferenciación de marca, adquisición de clientes ineficiente.",
    [UIStringKeys.LabelCustomerChallenge]: "El Reto del Cliente (¿Qué problema enfrenta el *usuario final*?)",
    [UIStringKeys.PlaceholderCustomerChallenge]: "Ej: Abrumado por software complejo, no encuentra productos sostenibles, se siente desconectado de las marcas.",
    [UIStringKeys.LabelConsumerInvolvement]: "Nivel de Implicación del Consumidor",
    [UIStringKeys.LabelFunnelStage]: "Etapa Típica del Embudo para Interacción Objetivo",
    [UIStringKeys.LabelConsumerBarriers]: "Barreras/Fricciones Clave del Consumidor",
    [UIStringKeys.PlaceholderConsumerBarriers]: "Ej: Percepción de precio alto, onboarding complejo, falta de confianza",
    [UIStringKeys.LabelCurrentStrategy]: "¿Qué se ha intentado hasta ahora? (Brevemente)",
    [UIStringKeys.PlaceholderCurrentStrategy]: "Ej: Campañas en redes sociales, descuentos, contenido SEO",
    [UIStringKeys.AlertNonPDF]: "Por favor, sube un archivo PDF.",
    [UIStringKeys.PlaceholderAIWillGenerate]: "La IA generará esto basándose en tu entrada, siguiendo los principios de Rumelt...",
    [UIStringKeys.MessageFormulatingChallenge]: "Formulando el Núcleo del Reto Estratégico de Rumelt... esto puede tardar un momento.",
    [UIStringKeys.MessageGeneratingPrompts]: "Generando prompts inteligentes para Acciones Coherentes... por favor espera.",
    [UIStringKeys.ErrorGeneric]: "Ocurrió un error desconocido.",
    [UIStringKeys.ErrorChallengeNotFormulated]: "Asegúrate de que el Diagnóstico y la Política Guía de Rumelt estén formulados antes de generar prompts.",
    [UIStringKeys.ErrorDiagnosisNotComplete]: "Por favor, completa todos los campos principales en el paso de Diagnóstico antes de generar el núcleo del reto.",
    [UIStringKeys.TextNotSet]: "No establecido",
    [UIStringKeys.TextNotGenerated]: "No generado",
    [UIStringKeys.TextNoPromptsGenerated]: "Aún no se han generado prompts.",
    [UIStringKeys.SelectDefaultOption]: "Selecciona una opción...",

    [UIStringKeys.LanguageToggleEN]: "EN",
    [UIStringKeys.LanguageToggleES]: "ES",

    [UIStringKeys.StepperAriaLabel]: "Progreso",
    [UIStringKeys.LoadingSpinnerSR]: "Cargando...",
  },
};

export const getText = (lang: Language, key: UIStringKeys, replacements?: Record<string, string | number>): string => {
  let text = translations[lang]?.[key] || translations[Language.EN]?.[key] || `Missing translation for ${key}`; 
  if (replacements) {
    Object.keys(replacements).forEach(placeholder => {
      text = text.replace(`{${placeholder}}`, String(replacements[placeholder]));
    });
  }
  return text;
};


export const HELP_TOPICS_LIST: HelpTopic[] = [
  { id: "overview", questionKey: UIStringKeys.HelpTopic_Overview_Q, answerKey: UIStringKeys.HelpTopic_Overview_A },
  { id: "diagnosis", questionKey: UIStringKeys.HelpTopic_Diagnosis_Q, answerKey: UIStringKeys.HelpTopic_Diagnosis_A },
  { id: "challenge", questionKey: UIStringKeys.HelpTopic_ChallengeFormulation_Q, answerKey: UIStringKeys.HelpTopic_ChallengeFormulation_A },
  { id: "prompts", questionKey: UIStringKeys.HelpTopic_SmartPrompts_Q, answerKey: UIStringKeys.HelpTopic_SmartPrompts_A },
  { id: "export", questionKey: UIStringKeys.HelpTopic_Export_Q, answerKey: UIStringKeys.HelpTopic_Export_A },
  { id: "ai", questionKey: UIStringKeys.HelpTopic_AIGeneration_Q, answerKey: UIStringKeys.HelpTopic_AIGeneration_A },
  { id: "navigation", questionKey: UIStringKeys.HelpTopic_Navigation_Q, answerKey: UIStringKeys.HelpTopic_Navigation_A },
];

export const FEEDBACK_EMAIL_RECIPIENTS = "luisma.nunez@llyc.global,marta.devicente@llyc.global,cesar.diez@llyc.global";
