
import React, { useCallback } from 'react';
import { StrategySessionData, Language, UIStringKeys } from '../types';
import { getText } from '../constants';
import Card from './common/Card';
import Button from './common/Button';
import { DocumentTextIcon, CheckCircleIcon, BrainIcon } from './Icons';

interface ResultsStepProps {
  data: StrategySessionData;
  lang: Language;
}

const ResultsStep: React.FC<ResultsStepProps> = ({ data, lang }) => {
  const formatForExport = useCallback(() => {
    let output = `# ${getText(lang, UIStringKeys.AppName)} - ${getText(lang, UIStringKeys.HeaderResults)}\n\n`;

    output += `## 1. ${getText(lang, UIStringKeys.HeaderDiagnosis)}\n\n`;
    output += `**${getText(lang, UIStringKeys.LabelClientName)}:** ${data.diagnosis.clientName || getText(lang, UIStringKeys.TextNotSet)}\n`;
    output += `**${getText(lang, UIStringKeys.LabelProjectBudget)}:** ${data.diagnosis.projectBudget || getText(lang, UIStringKeys.TextNotSet)}\n`;
    if (data.diagnosis.briefingFileName) {
      output += `**${getText(lang, UIStringKeys.LabelUploadBriefing)}:** ${data.diagnosis.briefingFileName}\n`;
    }
    output += `**${getText(lang, UIStringKeys.LabelCustomerType)}:** ${data.diagnosis.customerType || getText(lang, UIStringKeys.TextNotSet)}\n`;
    output += `**${getText(lang, UIStringKeys.LabelMarketCategory)}:** ${data.diagnosis.market || getText(lang, UIStringKeys.TextNotSet)}\n`;
    output += `**${getText(lang, UIStringKeys.LabelSectorIndustry)}:** ${data.diagnosis.sector || getText(lang, UIStringKeys.TextNotSet)}\n`;
    output += `**${getText(lang, UIStringKeys.LabelProductService)}:** ${data.diagnosis.productOrService || getText(lang, UIStringKeys.TextNotSet)}\n`;
    output += `**${getText(lang, UIStringKeys.LabelCoreProblem)}:** ${data.diagnosis.coreProblemToSolve || getText(lang, UIStringKeys.TextNotSet)}\n`;
    output += `**${getText(lang, UIStringKeys.LabelConsumerInvolvement)}:** ${data.diagnosis.consumerContext.involvement || getText(lang, UIStringKeys.TextNotSet)}\n`;
    output += `**${getText(lang, UIStringKeys.LabelFunnelStage)}:** ${data.diagnosis.consumerContext.funnelStage || getText(lang, UIStringKeys.TextNotSet)}\n`;
    output += `**${getText(lang, UIStringKeys.LabelConsumerBarriers)}:** ${data.diagnosis.consumerContext.barriers || getText(lang, UIStringKeys.TextNotSet)}\n`;
    output += `**${getText(lang, UIStringKeys.LabelCurrentStrategy)}:** ${data.diagnosis.currentStrategyAttempt || getText(lang, UIStringKeys.TextNotSet)}\n\n`;

    output += `## 2. ${getText(lang, UIStringKeys.HeaderChallengeFormulation)}\n\n`;
    output += `### ${getText(lang, UIStringKeys.HeaderRumeltDiagnosis)}:\n${data.challenge.rumeltDiagnosis || getText(lang, UIStringKeys.TextNotGenerated)}\n\n`;
    output += `### ${getText(lang, UIStringKeys.HeaderRumeltGuidingPolicy)}:\n${data.challenge.rumeltGuidingPolicy || getText(lang, UIStringKeys.TextNotGenerated)}\n\n`;
    output += `### ${getText(lang, UIStringKeys.HeaderBehavioralJustification)}:\n${data.challenge.behavioralJustification || getText(lang, UIStringKeys.TextNotGenerated)}\n\n`;
    output += `### ${getText(lang, UIStringKeys.HeaderCulturalTension)}:\n${data.challenge.culturalTension || getText(lang, UIStringKeys.TextNotGenerated)}\n\n`;
    output += `### ${getText(lang, UIStringKeys.HeaderMarketOpportunity)}:\n${data.challenge.marketOpportunity || getText(lang, UIStringKeys.TextNotGenerated)}\n\n`;
    output += `### ${getText(lang, UIStringKeys.HeaderConsumerInsight)}:\n${data.challenge.consumerInsight || getText(lang, UIStringKeys.TextNotGenerated)}\n\n`;
    
    if (data.challenge.keyAssumptions) {
        output += `### ${getText(lang, UIStringKeys.HeaderKeyAssumptions)}:\n${data.challenge.keyAssumptions}\n\n`;
    }
    if (data.challenge.relevantMentalModels) {
        output += `### ${getText(lang, UIStringKeys.HeaderRelevantMentalModels)}:\n${data.challenge.relevantMentalModels}\n\n`;
    }
    
    output += `## 3. ${getText(lang, UIStringKeys.HeaderSmartPrompts)}\n\n`;
    if (data.generatedPrompts.length > 0) {
      data.generatedPrompts.forEach((prompt) => {
        output += `* ${prompt}\n`; 
      });
    } else {
      output += `_${getText(lang, UIStringKeys.TextNoPromptsGenerated)}_\n`; 
    }
    output += `\n---\n_Generated by ${getText(lang, UIStringKeys.AppName)}_`;
    return output;
  }, [data, lang]);

  const handleCopyToClipboard = useCallback(() => {
    const textToCopy = formatForExport();
    navigator.clipboard.writeText(textToCopy)
      .then(() => alert(getText(lang, UIStringKeys.ResultsCopied)))
      .catch(err => alert(getText(lang, UIStringKeys.FailedToCopyResults) + err));
  }, [formatForExport, lang]);

  const handleDownloadTextFile = useCallback(() => {
    const textToDownload = formatForExport();
    const element = document.createElement("a");
    const file = new Blob([textToDownload], {type: 'text/markdown;charset=utf-8'}); 
    element.href = URL.createObjectURL(file);
    element.download = "Strategic_Challenge_Summary_Rumelt.md"; // Updated filename
    document.body.appendChild(element); 
    element.click();
    document.body.removeChild(element);
  }, [formatForExport]);

  return (
    <div className="space-y-8 animate-fadeIn">
      <h2 className="text-2xl font-semibold text-[#36A7B7] mb-2 flex items-center font-['Montserrat']"> 
        <CheckCircleIcon className="w-7 h-7 mr-2 text-[#76CC9B]" /> 
        {getText(lang, UIStringKeys.HeaderResults)}
      </h2>
      <p className="text-[#6D7475] mb-6 font-['Open_Sans']"> 
        {getText(lang, UIStringKeys.DescriptionResults)}
      </p>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card title={getText(lang, UIStringKeys.HeaderDiagnosisSnapshot)} className="max-h-[300px] overflow-y-auto"> 
          <ul className="space-y-1 text-sm text-[#0A263B] font-['Open_Sans']"> 
            <li><strong>{getText(lang, UIStringKeys.LabelClientName)}:</strong> {data.diagnosis.clientName || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
            <li><strong>{getText(lang, UIStringKeys.LabelProjectBudget)}:</strong> {data.diagnosis.projectBudget || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
            <li><strong>{getText(lang, UIStringKeys.LabelCustomerType)}:</strong> {data.diagnosis.customerType || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
            <li><strong>{getText(lang, UIStringKeys.LabelMarketCategory)}:</strong> {data.diagnosis.market || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
            <li><strong>{getText(lang, UIStringKeys.LabelSectorIndustry)}:</strong> {data.diagnosis.sector || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
            <li><strong>{getText(lang, UIStringKeys.LabelProductService)}:</strong> {data.diagnosis.productOrService || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
            <li><strong>{getText(lang, UIStringKeys.LabelCoreProblem)}:</strong> {data.diagnosis.coreProblemToSolve || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
            <li><strong>{getText(lang, UIStringKeys.LabelConsumerInvolvement)}:</strong> {data.diagnosis.consumerContext.involvement || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
            <li><strong>{getText(lang, UIStringKeys.LabelFunnelStage)}:</strong> {data.diagnosis.consumerContext.funnelStage || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
            <li><strong>{getText(lang, UIStringKeys.LabelConsumerBarriers)}:</strong> {data.diagnosis.consumerContext.barriers || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotSet)}</span>}</li>
          </ul>
        </Card>

        <Card title={getText(lang, UIStringKeys.HeaderStrategicChallengeCore)} className="max-h-[300px] overflow-y-auto"> 
          <div className="text-sm text-[#0A263B] font-['Open_Sans'] space-y-2"> 
            <p><strong className="text-[#F54963] font-['Montserrat']">{getText(lang, UIStringKeys.HeaderRumeltDiagnosis)}:</strong> {data.challenge.rumeltDiagnosis || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotGenerated)}</span>}</p>
            <p><strong className="text-[#36A7B7] font-['Montserrat']">{getText(lang, UIStringKeys.HeaderRumeltGuidingPolicy)}:</strong> {data.challenge.rumeltGuidingPolicy || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotGenerated)}</span>}</p>
            <p><strong className="text-[#FC6B08] font-['Montserrat'] flex items-center"><BrainIcon className="w-4 h-4 mr-1.5"/>{getText(lang, UIStringKeys.HeaderBehavioralJustification)}:</strong> {data.challenge.behavioralJustification || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotGenerated)}</span>}</p>
            <p><strong className="text-[#8B8BB2] font-['Montserrat']">{getText(lang, UIStringKeys.HeaderCulturalTension)}:</strong> {data.challenge.culturalTension || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotGenerated)}</span>}</p>
            <p><strong className="text-[#76CC9B] font-['Montserrat']">{getText(lang, UIStringKeys.HeaderMarketOpportunity)}:</strong> {data.challenge.marketOpportunity || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotGenerated)}</span>}</p>
            <p><strong className="text-[#FC6B08] font-['Montserrat']">{getText(lang, UIStringKeys.HeaderConsumerInsight)}:</strong> {data.challenge.consumerInsight || <span className="text-[#878E90]">{getText(lang, UIStringKeys.TextNotGenerated)}</span>}</p>
          </div>
        </Card>
      </div>

      <Card title={getText(lang, UIStringKeys.HeaderGeneratedIdeationPrompts)} className="max-h-[300px] overflow-y-auto"> 
        {data.generatedPrompts.length > 0 ? (
          <ul className="space-y-2">
            {data.generatedPrompts.map((prompt, index) => (
              <li key={index} className="p-3 bg-[#F8F8F8] border border-[#DDDDDD] rounded-md text-sm text-[#0A263B] font-['Open_Sans']"> 
                {prompt}
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-[#878E90] font-['Open_Sans']">{getText(lang, UIStringKeys.TextNoPromptsGenerated)}</p> 
        )}
      </Card>
      
      <div className="mt-8 flex flex-col sm:flex-row gap-4 justify-center">
        <Button onClick={handleCopyToClipboard} variant="secondary" icon={<DocumentTextIcon className="w-5 h-5"/>}>
          {getText(lang, UIStringKeys.CopyToClipboard)}
        </Button>
        <Button onClick={handleDownloadTextFile} variant="primary" icon={<DocumentTextIcon className="w-5 h-5"/>}>
          {getText(lang, UIStringKeys.DownloadAsMD)}
        </Button>
      </div>

    </div>
  );
};

export default ResultsStep;